/**
 * Edequate. Copyright (C) 2017-18 Edeqa <http://www.edeqa.com>
 *
 * Created 12/27/17.
 *
 * !!! IMPORTANT !!!
 * DO NOT EDIT THIS FILE
 * !!! IMPORTANT !!!
 */

function Main(u) {
    var self = this;

    this.start = function(startOptions) {
        startOptions = startOptions || {};

        var info = startOptions.info;
        var type = startOptions.type || "main";

        self.layout = u.create(HTML.DIV, {className:"layout"}, document.body);
        self.actionbar = u.actionBar({
            title: "Loading...",
            onbuttonclick: function(){
                try {
                    self.drawer.open();
                } catch(e) {
                    console.error(e);
                }
            }
        }, document.body);

        self.selectLang = u.create(HTML.SELECT, { className: "actionbar-select-lang changeable", value: u.load("lang"), onchange: function(e, event) {
            var lang = (this.value || navigator.language).toLowerCase().slice(0,2);
            u.save("lang", lang);
            self.loadResources("main.json");
            self.holder.resume();
        }}, self.actionbar).place(HTML.OPTION, { name: u.lang.loading, value:"" });

        u.getJSON("/rest/locales").then(function(json){
            console.log("locales", json.message);
            u.clear(self.selectLang);
            var count = 1;
            self.selectLang.place(HTML.OPTION, { innerHTML: "Default", value: "en" });
            for(var x in json.message) {
                self.selectLang.place(HTML.OPTION, { innerHTML: json.message[x], value: x });
                if(u.load("lang") === x) self.selectLang.selectedIndex = count;
                count++;
            }
        });

        this.loadResources("main.json", function() {
            var dialogAbout = u.dialog({
                className: "about-dialog",
                itemsClassName: "about-dialog-items",
                buttonsClassName: "about-dialog-buttons",
                items: [
                    { innerHTML: "Edequate" },
                    { innerHTML: "&nbsp;" },
                    { content: [
                        u.create(HTML.IMG, {src: "/images/edeqa-logo.svg", className: "about-dialog-edeqa-logo"}),
                        u.create(HTML.DIV)
                            .place(HTML.DIV, { innerHTML: "Copyright &copy;2017-18 Edeqa" })
                            .place(HTML.A, {className: "about-dialog-edeqa-link", href: "http://www.edeqa.com", target: "_blank", rel:"noopener", innerHTML: "http://www.edeqa.com" })
                    ]
                    },
                    { enclosed: true, label: u.lang.legal_information || "Legal information", body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum." },
                ],
                positive: {
                    label: u.lang.ok
                }
            });

            self.drawer = new u.drawer({
                title: u.lang.title || "Title",
                collapsed: u.load("drawer:collapsed"),
                logo: {
                    src: "/images/logo.svg"
                },
                onprimaryclick: function(){
                    console.log("onprimaryclick");
                },
                footer: {
                    className: "drawer-footer-label",
                    content: [
                        u.create(HTML.DIV, { className: "drawer-footer-link", innerHTML: "Powered with Edequate", onclick: function(e){
                            dialogAbout.open();
                        }})
                    ]
                },
                sections: {
                    "0": u.lang.drawer_primary,
                    "1": u.lang.drawer_summary,
                    "2": u.lang.drawer_main,
                    "3": u.lang.drawer_explore,
                    "4": u.lang.drawer_share,
                    "5": u.lang.drawer_resources,
                    "6": u.lang.drawer_miscellaneous,
                    "7": u.lang.drawer_settings,
                    "8": u.lang.drawer_help,
                    "9": u.lang.drawer_last
                }
            }, document.body);

            u.getJSON("/rest/" + type).then(function(json){
                console.log("holders", json);
                for(var i in json.message) {
                    json.message[i] = json.extra + "/" + json.message[i].replace(".js","");
                }
                u.eventBus.register(json.message, {
                    context: self,
                    onprogress: function (loaded) {
                        u.byId("loading-dialog-progress").innerHTML = Math.ceil(loaded / json.message.length * 100) + "%";
                    },
                    onstart: function () {
                        console.log(u.eventBus.holders)
                    },
                    onsuccess: function () {
                        for(var x in u.eventBus.holders) {
                            var holder = u.eventBus.holders[x];
                            if(holder.menu) {
                                self.drawer.add(holder.category, holder.type, holder.menu, holder.icon, function(){
                                    self.drawer.toggleSize(false);
                                    self.actionbar.toggleSize(false);

                                    self.content.scrollTop = 0;
                                    window.history.pushState({}, null, "/main/" + this.type);

                                    self.drawer.close();
                                    self.holder = this;
                                    if(this.resume) {
                                        this.resume();
                                    }

                                    self.actionbar.setTitle(this.title);
                                    return false;
                                }.bind(holder));
                            }
                        }

                        if(info) {
                            self.content.innerHTML = info;
                            self.actionbar.setTitle(u.lang.info);
                            u.byId("loading-dialog").hide();
                        } else {
                            var urlPath = new URL(window.location);
                            var path = urlPath.path.split("/");
                            if(path.length > 2 && path[1].toLowerCase() == "main") {
                                path = path[2];
                            } else {
                                path = "home";
                           }
                           var holder = u.eventBus.holders[path.toLowerCase()];
                           self.actionbar.setTitle(holder.title);
                           self.holder = holder;
                           holder.resume();
                        }
                        u.byId("loading-dialog").hide();

                    },
                    onerror: function (code, origin, error) {
                        console.error(code, origin, error);
                    }
                });
            });

            var switchFullDrawer = function(){
                if(self.content.scrollTop > 200) {

                    self.drawer.toggleSize(true);
                    self.actionbar.toggleSize(true);
//                    clearTimeout(self.buttonScrollTop.hideTimeout);
                    if(!self.buttonScrollTop.offsetHeight) {
                        self.buttonScrollTop.hideTimeout = setTimeout(function(){
                            self.buttonScrollTop.hide(/*HIDING.OPACITY*/);
                        }, 1500);
                    }
                    self.buttonScrollTop.show(/*HIDING.OPACITY*/);
                } else {
                    self.drawer.toggleSize(false);
                    self.actionbar.toggleSize(false);
                    if(self.buttonScrollTop.offsetHeight) {
                        self.buttonScrollTop.hide(/*HIDING.OPACITY*/);
                    }
                }
            };
            self.content = u.create(HTML.DIV, {className:"content", onscroll: switchFullDrawer}, self.layout);

            self.buttonScrollTop = u.create(HTML.BUTTON, {
                className: "icon button-scroll-top changeable hidden",
                onclick: function() {
                    self.content.scrollTop = 0;
                    switchFullDrawer.call(self.content);
                },
                innerHTML: "keyboard_arrow_up"
            }, self.layout);
        });
    };

    this.loadResources = function(resource, callback) {
        var lang = (u.load("lang") || navigator.language).toLowerCase().slice(0,2);
        u.lang.overrideResources({
            "default": "/resources/en/" + resource,
            resources: "/rest/resources",
            resource: resource,
            locale: lang,
            callback: callback
        });
    }

}